
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://luckyprogram.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Kevin Hong"
title: "{ Kevin Hong }"
description: "Personal website and portfolio for Kevin Hong. Hand crafted and custom personalized website."
keywords: "hong, kevin, data, website, portfolio"
favicon: "/img/favicon_clover.ico"

################
# Header layout #
################

black-favicon:
logo: # leave blank if you don't want a logo

background-img: "../img/tech.gif"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "“Information is the oil of the 21st century, and analytics is the combustion engine.”"
  - text: "“Data are just summaries of thousands of stories—tell a few of those stories to help make the data meaningful.”"
  - text: "“No data is clean, but most is useful.”"

me-img: "/img/me.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/clovey-36p.png"
icon-48p: "/img/web-app/clovey-48p.png"
icon-72p: "/img/web-app/clovey-72p.png"
icon-96p: "/img/web-app/clovey-96p.png"
icon-144p: "/img/web-app/clovey-144p.png"
icon-192p: "/img/web-app/clovey-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "kevin-hong-personal"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/movie.png"
    date: "May 2021"
    description: "CMSE 202 MSU Coding Project"
    link: "https://github.com/LuCkYProgram/CMSE202_Hong"
  - image: "/img/timeline/brain.jpg"
    date: "June 2021"
    description: "Parkinson's Basic Machine Learning"
    link: "https://github.com/LuCkYProgram/Parkinsons-Basic-Machine-Learning"
  - image: "/img/timeline/msuai.png"
    date: "September 2021 - `Present/Ongoing`"
    description: "Attendance Project - MSU AI Club"
    link: "https://github.com/MSU-AI/Attendance-Project"
  - image: "/img/timeline/fruit.jpg"
    date: "March 2022"
    description: "Fruit Ninja AR"
    link: "https://github.com/LuCkYProgram/Fruit-Ninja-AR"
  - image: "/img/timeline/discord.jpg"
    date: "July 2022 - Ongoing"
    description: "Clovey v2 - Discord Bot"
    link: "https://github.com/LuCkYProgram/cloveyv2"

# First image of the Timeline

timeline-img: "/img/timeline/lucky.png"

###########
# Contact #
###########

email: "hkevin090602@gmail.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Kevin Hong is a junior at the University of Michigan. He always is eager to learn new things and tell the stories of what numbers represent everyday."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/LuCkYProgram"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/hong-kevin-843987204/"


############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: 
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Featured: 'latest-post'
  Projects: 'timeline'
  Contact / Resume: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
